# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  build:
    project: .\TestCpp.sln
# configuration for all other branches except "master"
-
  branches:
    except:
      - master
  configuration: Debug
  build:
    project: .\TestCpp.sln
